# Generated by Django 2.2 on 2020-07-02 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200702_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='essay',
            name='text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
