# Generated by Django 2.2 on 2020-07-03 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_essay_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcategory',
            name='image_url',
            field=models.TextField(default='https://photagon.com/blog/wp-content/uploads/2018/02/photagon_nature.jpg'),
            preserve_default=False,
        ),
    ]
